name: Build

on:
  push:
    branches: [main]
env:
  DASHBOARD_URL: https://487e70298bb46994-94-70-215-151.serveousercontent.com #serveo url for localhost reverse proxy for demo

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build.outputs.digest }}

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          provenance: false

      - uses: alextsoh/secure-pipeline-action@921ba58d6d49059026a78d161f51a549539545d8
        with:
          image: ghcr.io/${{ github.repository }}@${{ steps.build.outputs.digest }}
          dashboard-url: ${{ env.DASHBOARD_URL }}

  provenance:
    needs: [build]
    permissions:
      actions: read
      id-token: write
      packages: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v2.0.0
    with:
      image: ghcr.io/${{ github.repository }}
      digest: ${{ needs.build.outputs.digest }}
      registry-username: ${{ github.actor }}
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}